config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :persons

  root to: "chen#home"

  resources :pets do
    put 'like', to: 'pets#click_on_like', as: 'my_like'
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
    has_one :person
    has_one :pet
end

app/models/person.rb
class Person < ActiveRecord::Base
    has_many :pets, :foreign_key => 'owner_id'
    has_many :likes
end

app/models/pet.rb
class Pet < ActiveRecord::Base
    belongs_to :person, :class_name => "Person", :foreign_key => 'owner_id'
    has_many :like

    enum kind: [ :dog, :cat, :monkey]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chen_controller.rb
class ChenController < ApplicationController
end

app/controllers/homepage_controller.rb
class HomepageController < ActionController::Base
    layout "application"
    def home
    end
  end
  

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @pets = @person.pets
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :age, :date_of_birth)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def click_on_like
    @pet = Pet.find(params[:pet_id])
    @like = Like.where(owner_id: @pet.owner_id, pet_id: @pet.id)
    if(@like.nil? || @like.length() > 0)
      redirect_to pet_path(@pet)
    elsif @pet.owner_id != 1 # current_user
      byebug
      Like.create(owner_id: @pet.owner_id, pet_id: @pet.id)
      redirect_to pet_path(@pet)
    else
      redirect_to pet_path(@pet)
    end
  end

  private
    # Use callbacks to share common setup or constLikesraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :kind, :owner_id, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pets_helper.rb
module PetsHelper

    def pets_table(pets)
        result = StringIO.new

        columns = ['Name', 'Kind', 'Owner', 'Date of birth']
        result << content_tag(:table) do
          content_tag(:thead) do
            content_tag(:tr) do 
              columns.map {|c| concat content_tag(:th, c)}
            end    
          end
        end
        result.string.html_safe
      end


=begin
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Owner</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.name %></td>
          <td><%= pet.kind %></td>
          <td><%= pet.owner_id %></td>
          <td><%= pet.date_of_birth %></td>
          <td><%= link_to 'Show', pet %></td>
          <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
          <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</tbody>
</table>


    
=end


end

app/views/chen/home.html.erb
<div> mordechay and chen tirgul</div>

app/views/homepage/home.html.erb
<h1>Hello, World!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Petsbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <%= link_to "Home", root_path %>
  <%= link_to "Pets", pets_path %>
  <%= link_to "People", people_path %>
</div>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Date of birth</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.age %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= person.id %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @person.date_of_birth %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Owner</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.name %></td>
          <td><%= pet.kind %></td>
          <td><%= pet.owner_id %></td>
          <td><%= pet.date_of_birth %></td>
          <td><%= link_to 'Show', pet %></td>
          <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
          <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/persons/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/persons/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', person_path %>

app/views/persons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @person.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.age %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/persons/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', person_path %>

app/views/persons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @person.date_of_birth %>
</p>



<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', person_path %>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.select :kind, Pet.kinds.keys.map {|k| [k.humanize, k]} %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>
<%= pets_table(@pets) %>
<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @pet.kind %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner_id %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @pet.date_of_birth %>
</p>

<p>
  <%= button_to "Like", pet_my_like_path(@pet.id), method: "put" %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @pet.like.length()%>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>